print("\n \033[1;32;40m  |   |   ")
print("   |   |   ")
print("   |   |   ")
print("-----------")
print("   |   |   ")
print("   |   |   ")
print("   |   |   ")
print("-----------")
print("   |   |   ")
print("   |   |   ")
print("   |   |   \n")